### ISSUE TITLE
[BUG]Questions about bowl drop

### ISSUE THREAD

**Issue by Pau1am** [ShaneBeeStudios/SurvivalPlus#1] opened 2020-05-01 13:22 UTC
**Describe the bug**
I found that when I throw more than one bowl into the water at a time, these bowls cannot hold water. But when I throw out only one bowl at a time, it can hold water normally

**To Reproduce**
1.Holding more than one bowl
2.Continuously throw the bowl into the water
3.The bowl is not filled with water

**Expected behavior**
I think that when I throw out multiple bowls into the water, it should also hold water

**Screenshots/Errors**
![image](https://user-images.githubusercontent.com/41251296/80808293-ce22fc80-8bf1-11ea-8b52-76e2f72ef57c.png)

**Version Info:**
 - **Plugin Version:**3.11.2
 - **Server Version/Platform** paper 1.15.2

**Additional context**
Nothing

**Comment by ShaneBeee** [comment] 2020-05-01 19:34
I can't remember if this was intended or not, but I'll look into fixing it.

**Comment by ShaneBeee** [comment] 2020-05-01 22:25
Fixed in latest update

**Closed as completed** 2020-05-01 22:25 UTC
Labels: bug, completed
